spring.application.name=neovision

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/neovision_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=NeoVision2026SecretKeyForJWTTokenGenerationUniversidadElBosqueOptometria
jwt.expiration=86400000
